default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  username:
  password: 

development:
  <<: *default
  database: spms_development_db
test: &test
  <<: *default
  database: spms_test_db


staging:
  <<: *default
  url:  <%= ENV['DATABASE_URL'] %>
  pool: <%= ENV['DB_POOL'] || ENV['RAILS_MAX_THREADS'] || 5 %>

qa:
  <<: *default
  url:  <%= ENV['DATABASE_URL'] %>
  pool: <%= ENV['DB_POOL'] || ENV['RAILS_MAX_THREADS'] || 5 %>


cucumber:
  <<: *test
